//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingPlanner.Resources.Views.Meeting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Edit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Edit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeetingPlanner.Resources.Views.Meeting.Edit", typeof(Edit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convenient.
        /// </summary>
        public static string Convenient {
            get {
                return ResourceManager.GetString("Convenient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string CountButton {
            get {
                return ResourceManager.GetString("CountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to results.
        /// </summary>
        public static string GoToResult {
            get {
                return ResourceManager.GetString("GoToResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconvenient.
        /// </summary>
        public static string Inconvenient {
            get {
                return ResourceManager.GetString("Inconvenient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a convenient and inconvenient for you days, and then click the send button.
        /// </summary>
        public static string PleaseSelectDays {
            get {
                return ResourceManager.GetString("PleaseSelectDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to other participants of the meeting room, so that they can join the planning.
        /// </summary>
        public static string SendNumerToFriends {
            get {
                return ResourceManager.GetString("SendNumerToFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of your friends had planned a meeting.
        /// </summary>
        public static string SomeBodeCreatesMeeting {
            get {
                return ResourceManager.GetString("SomeBodeCreatesMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but no such meeting planned.
        /// </summary>
        public static string SorryNoMeeting {
            get {
                return ResourceManager.GetString("SorryNoMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name(not necessarily).
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
