//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 1573
namespace DataAccess
{
    using System;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeetingPlannerContainer : DbContext
    {
        static MeetingPlannerContainer()
    	{ 
    		Database.SetInitializer<MeetingPlannerContainer>(null);
    	}
    	
    	public MeetingPlannerContainer() : base("name=MeetingPlannerContainer")
        {
        }
    	
    	public MeetingPlannerContainer(string nameOrConnectionString) : base(nameOrConnectionString)
    	{	
    	}
    
    	public MeetingPlannerContainer(string nameOrConnectionString, DbCompiledModel model) : base(nameOrConnectionString, model)
    	{
    	}
    
    	public MeetingPlannerContainer(DbConnection existingConnection, bool contextOwnsConnection) : base(existingConnection, contextOwnsConnection)
    	{
    	}
    
    	public MeetingPlannerContainer(DbConnection existingConnection, DbCompiledModel model, bool contextOwnsConnection) : base(existingConnection, model, contextOwnsConnection)
    	{
    	}
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {		
    		modelBuilder.Configurations.Add(new CachedUserName_Mapping());
    		modelBuilder.Configurations.Add(new Meeting_Mapping());
    		modelBuilder.Configurations.Add(new MeetingMembers_Mapping());
    		modelBuilder.Configurations.Add(new MeetingStatus_Mapping());
    		modelBuilder.Configurations.Add(new UserMeetingDates_Mapping());
    		modelBuilder.Configurations.Add(new UserProfile_Mapping());
    		modelBuilder.Configurations.Add(new webpages_Membership_Mapping());
    		modelBuilder.Configurations.Add(new webpages_OAuthMembership_Mapping());
    		modelBuilder.Configurations.Add(new webpages_Roles_Mapping());
        }
    	
        public DbSet<Meeting> MeetingSet { get; set; }
        public DbSet<MeetingStatus> MeetingStatusSet { get; set; }
        public DbSet<MeetingMembers> MeetingMembersSet { get; set; }
        public DbSet<UserMeetingDates> UserMeetingDatesSet { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<CachedUserName> CachedUserNames { get; set; }
    }
}
