//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class webpages_OAuthMembership_Mapping : EntityTypeConfiguration<webpages_OAuthMembership>
    {
        public webpages_OAuthMembership_Mapping()
        {                        
              this.HasKey(t => new {t.Provider, t.ProviderUserId});        
              this.ToTable("webpages_OAuthMembership");
              this.Property(t => t.Provider).HasColumnName("Provider").IsRequired().HasMaxLength(30);
              this.Property(t => t.ProviderUserId).HasColumnName("ProviderUserId").IsRequired().HasMaxLength(100);
              this.Property(t => t.UserId).HasColumnName("UserId");
         }
    }
}
