//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class webpages_Membership_Mapping : EntityTypeConfiguration<webpages_Membership>
    {
        public webpages_Membership_Mapping()
        {                        
              this.HasKey(t => t.UserId);        
              this.ToTable("webpages_Membership");
              this.Property(t => t.UserId).HasColumnName("UserId").HasDatabaseGeneratedOption(new Nullable<DatabaseGeneratedOption>(DatabaseGeneratedOption.None));
              this.Property(t => t.CreateDate).HasColumnName("CreateDate");
              this.Property(t => t.ConfirmationToken).HasColumnName("ConfirmationToken").HasMaxLength(128);
              this.Property(t => t.IsConfirmed).HasColumnName("IsConfirmed");
              this.Property(t => t.LastPasswordFailureDate).HasColumnName("LastPasswordFailureDate");
              this.Property(t => t.PasswordFailuresSinceLastSuccess).HasColumnName("PasswordFailuresSinceLastSuccess");
              this.Property(t => t.Password).HasColumnName("Password").IsRequired().HasMaxLength(128);
              this.Property(t => t.PasswordChangedDate).HasColumnName("PasswordChangedDate");
              this.Property(t => t.PasswordSalt).HasColumnName("PasswordSalt").IsRequired().HasMaxLength(128);
              this.Property(t => t.PasswordVerificationToken).HasColumnName("PasswordVerificationToken").HasMaxLength(128);
              this.Property(t => t.PasswordVerificationTokenExpirationDate).HasColumnName("PasswordVerificationTokenExpirationDate");
         }
    }
}
