//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class webpages_Roles_Mapping : EntityTypeConfiguration<webpages_Roles>
    {
        public webpages_Roles_Mapping()
        {                        
              this.HasKey(t => t.RoleId);        
              this.ToTable("webpages_Roles");
              this.Property(t => t.RoleId).HasColumnName("RoleId");
              this.Property(t => t.RoleName).HasColumnName("RoleName").IsRequired().HasMaxLength(256);
    			this.HasMany(t => t.UserProfiles).WithMany(t => t.webpages_Roles)
    				.Map(m => 
    				{
    					m.ToTable("webpages_UsersInRoles");
    					m.MapLeftKey("webpages_Roles_RoleId");
    					m.MapRightKey("UserProfiles_Id");
    				});
         }
    }
}

